apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: amazezone
build:
  artifacts:
    - image: user-service
      context: user-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "**/*"
            src: .
manifests:
  rawYaml:
    - k8s/*
